version: '3.8'

services:
  backend:
    build: ../backend
    ports:
      - "${BACKEND_PORT}:8000"  # ← Uses .env variable
    env_file: .env  # ← Load all variables
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_URL=${REDIS_URL}
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}

  frontend:
    build: ../frontend
    ports:
      - "${FRONTEND_PORT}:5173"

  postgres:
    image: postgres:15
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  minio:
    image: minio/minio
    env_file: .env
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  celery:
    build: ../backend
    env_file: .env
    command: celery -A worker.celery worker --loglevel=info

volumes:
  postgres_data:
  minio_data: